import {
  PDFDocument, PDFName, PDFNumber,
  clip, endPath, fill, pushGraphicsState, popGraphicsState, rectangle, setFillingRgbColor, stroke,
} from '@cantoo/pdf-lib';

/**
 * Builds a real PDF from a declarative list of form elements.
 *
 * Real, not a mock: every case in this corpus goes through `PDFDocument.save()`
 * and back through `PDFDocument.load()`, so the detectors read bytes off a
 * parsed document exactly as they do a file somebody opened. A hand-built
 * object graph would let a case pass while the real parse path was broken.
 *
 * Nothing here is committed as a `.pdf`. A binary fixture is opaque in review,
 * cannot say which element it is exercising, and has to be regenerated by
 * hand when the vocabulary grows; a spec is readable in the diff and the
 * corpus stays extensible. The three committed PDFs the corpus also runs are
 * real documents from the field and are the point of comparison - see
 * `README.md`.
 *
 * `corpus.js` holds the cases and their expectations. This module only builds.
 */

/** `/F` annotation flags, and `/Ff` field flags, by the name a case uses. */
const ANNOTATION_FLAGS = { hidden: 0b10, print: 0b100, noView: 0b100000 };

/**
 * One page's worth of elements.
 *
 * @typedef {object} PageSpec
 * @property {[number, number]} [size] default `[400, 300]`.
 * @property {number} [rotation] `/Rotate`, in degrees.
 * @property {[number, number, number, number]} [cropBox] `x, y, width, height`.
 * @property {WidgetSpec[]} [widgets] live AcroForm fields.
 * @property {InkSpec[]} [ink] shapes drawn into the page's own content stream.
 */

/**
 * A live AcroForm field. `x/y/width/height` is its `/Rect`, in PDF user space.
 *
 * @typedef {object} WidgetSpec
 * @property {'text'|'checkbox'|'radio'|'signature'|'pushButton'|'dropdown'} widget
 * @property {number} x
 * @property {number} y
 * @property {number} width
 * @property {number} height
 * @property {number} [comb] `/MaxLen` with the comb flag set: a run of N boxes.
 * @property {boolean} [multiline]
 * @property {boolean} [required]
 * @property {boolean} [readOnly] text fields and checkboxes alike.
 * @property {'hidden'|'print'|'noView'} [flag] set on the widget's own `/F`.
 * @property {Array<{x: number, y: number, width: number, height: number}>} [options]
 *   radio only: one rectangle per option.
 */

/**
 * Ink drawn into the page's own content stream - what a *flat* form has
 * instead of widgets, and the only thing `pageInk.js` can see.
 *
 * @typedef {object} InkSpec
 * @property {'rect'|'paintedRect'|'line'|'combTeeth'|'boxedComb'|'cellRow'|'clipRect'} ink
 */

const DEFAULT_SIZE = [400, 300];

function addTextWidget(form, page, spec, id) {
  const field = form.createTextField(spec.name ?? `text_${id}`);
  if (spec.comb) {
    field.setMaxLength(spec.comb);
    field.enableCombing();
  }
  if (spec.multiline) field.enableMultiline();
  if (spec.required) field.enableRequired();
  // Read-only last: pdf-lib's other setters are happy either way, but a
  // read-only field is the one state where "set it, then configure it" reads
  // like a mistake to anyone scanning the fixture.
  if (spec.readOnly) field.enableReadOnly();
  field.addToPage(page, pick(spec));
  return field;
}

/** Just the rectangle, so a spec can carry flags pdf-lib would reject. */
const pick = ({ x, y, width, height }) => ({ x, y, width, height });

function addWidget(form, page, spec, id) {
  switch (spec.widget) {
    case 'text':
      return addTextWidget(form, page, spec, id);
    case 'checkbox': {
      const field = form.createCheckBox(spec.name ?? `check_${id}`);
      field.addToPage(page, pick(spec));
      if (spec.readOnly) field.enableReadOnly();
      return field;
    }
    case 'radio': {
      const group = form.createRadioGroup(spec.name ?? `radio_${id}`);
      spec.options.forEach((option, index) => group.addOptionToPage(`option_${index}`, page, pick(option)));
      return group;
    }
    case 'signature': {
      // pdf-lib has no signature-field API, so this is a text field with its
      // `/FT` changed - which is exactly what a `/Sig` widget is at the object
      // level, and the only thing any detector here looks at.
      const field = form.createTextField(spec.name ?? `sig_${id}`);
      field.addToPage(page, pick(spec));
      field.acroField.dict.set(PDFName.of('FT'), PDFName.of('Sig'));
      return field;
    }
    case 'pushButton':
      return form.createButton(spec.name ?? `button_${id}`)
        .addToPage(spec.label ?? 'Go', page, pick(spec));
    case 'dropdown': {
      const field = form.createDropdown(spec.name ?? `choice_${id}`);
      field.addOptions(spec.options ?? ['one', 'two']);
      field.addToPage(page, pick(spec));
      return field;
    }
    default:
      throw new Error(`Unknown widget kind: ${spec.widget}`);
  }
}

/**
 * Sets `/F` on the widgets a spec flagged.
 *
 * After the whole page is built, and by annotation index, because pdf-lib's
 * `addToPage` owns the annotation while it is being created and offers no
 * hook for the flag.
 */
function applyAnnotationFlags(page, widgets) {
  const annots = page.node.Annots();
  if (!annots) return;
  let index = 0;
  for (const spec of widgets) {
    const count = spec.widget === 'radio' ? spec.options.length : 1;
    if (spec.flag) {
      for (let n = 0; n < count; n += 1) {
        const annot = page.doc.context.lookup(annots.get(index + n));
        annot.set(PDFName.of('F'), PDFNumber.of(ANNOTATION_FLAGS[spec.flag]));
      }
    }
    index += count;
  }
}

/**
 * A run of `cells` teeth: short vertical ticks at a constant pitch, standing
 * on a horizontal writing line. This is how a printed form marks "one
 * character per box" without drawing boxes - income tax form 101's shape.
 */
function drawCombTeeth(page, { x, y, pitch, cells, toothHeight = 6, thickness = 0.8, ruleWidth }) {
  const width = ruleWidth ?? pitch * cells;
  page.drawLine({ start: { x, y }, end: { x: x + width, y }, thickness });
  for (let cell = 0; cell <= cells; cell += 1) {
    const tickX = x + cell * pitch;
    page.drawLine({ start: { x: tickX, y }, end: { x: tickX, y: y + toothHeight }, thickness });
  }
}

/** A run of `cells` closed boxes, drawn edge to edge - the practice form's shape. */
function drawBoxedComb(page, { x, y, pitch, cells, height, thickness = 0.8 }) {
  for (let cell = 0; cell < cells; cell += 1) {
    page.drawRectangle({
      x: x + cell * pitch, y, width: pitch, height, borderWidth: thickness, borderColor: BLACK,
    });
  }
}

/**
 * One ruled row divided into `columns` cells: two horizontal rules and
 * `columns + 1` verticals. `formCells.js` needs at least one interior wall
 * before it will call a row a form row rather than a decorative panel, so a
 * single undivided rectangle is deliberately a different spec (`rect`).
 */
function drawCellRow(page, { x, y, width, height, columns, thickness = 0.8 }) {
  const step = width / columns;
  page.drawLine({ start: { x, y }, end: { x: x + width, y }, thickness });
  page.drawLine({ start: { x, y: y + height }, end: { x: x + width, y: y + height }, thickness });
  for (let wall = 0; wall <= columns; wall += 1) {
    const wallX = x + wall * step;
    page.drawLine({ start: { x: wallX, y }, end: { x: wallX, y: y + height }, thickness });
  }
}

const BLACK = { type: 'RGB', red: 0, green: 0, blue: 0 };

/**
 * A rectangle painted with the `re` operator, which is the *only* way to put
 * one in `ink.rects`.
 *
 * pdf-lib's own `drawRectangle` never emits `re`: it builds every rectangle
 * as `m/l/l/l/h`, so it lands in `ink.verticals`/`ink.horizontals` and
 * `findCheckboxes` - which reads `ink.rects` alone - cannot see it. Our
 * practice form is pdf-lib's output and has exactly that shape. Real-world
 * producers do both, which is why `pageInk.js` normalizes both, so a corpus
 * that could only express one half would leave `findCheckboxes` uncovered.
 */
function drawPaintedRect(page, { x, y, width, height, fillRect = true }) {
  page.pushOperators(
    pushGraphicsState(),
    setFillingRgbColor(0, 0, 0),
    rectangle(x, y, width, height),
    fillRect ? fill() : stroke(),
    popGraphicsState(),
  );
}

/**
 * A rectangle used as a clipping path: `re W n`, which paints nothing.
 *
 * Its own spec rather than a flag, because it is the one shape whose whole
 * point is that the detectors must NOT see it. The health declaration issues
 * 1,027 of these, and counting them as boxes invented 76 phantom 13.3x10.8
 * "checkboxes" (`pageInk.js`'s docstring). `n` ends a path without painting
 * it, so only the painting operators may publish.
 */
function drawClipRect(page, { x, y, width, height }) {
  page.pushOperators(
    pushGraphicsState(),
    rectangle(x, y, width, height),
    clip(),
    endPath(),
    popGraphicsState(),
  );
}

function drawInk(page, spec) {
  switch (spec.ink) {
    case 'rect':
      return page.drawRectangle({
        x: spec.x, y: spec.y, width: spec.width, height: spec.height,
        borderWidth: spec.thickness ?? 0.8, borderColor: BLACK,
      });
    case 'line':
      return page.drawLine({
        start: { x: spec.x, y: spec.y },
        end: { x: spec.x2 ?? spec.x, y: spec.y2 ?? spec.y },
        thickness: spec.thickness ?? 0.8,
      });
    case 'combTeeth': return drawCombTeeth(page, spec);
    case 'boxedComb': return drawBoxedComb(page, spec);
    case 'cellRow': return drawCellRow(page, spec);
    case 'paintedRect': return drawPaintedRect(page, spec);
    case 'clipRect': return drawClipRect(page, spec);
    default:
      throw new Error(`Unknown ink kind: ${spec.ink}`);
  }
}

/**
 * Builds the document a case describes and returns it parsed, the way the
 * Sign tool receives one: saved to bytes and loaded back.
 *
 * @param {{pages: PageSpec[]} | PageSpec} spec a bare page spec is one page.
 * @returns {Promise<import('@cantoo/pdf-lib').PDFDocument>}
 */
export async function buildDocument(spec) {
  const pages = spec.pages ?? [spec];
  const doc = await PDFDocument.create();
  const form = doc.getForm();
  // A field name is unique per *document*, not per page, so the default
  // cannot be derived from the rectangle: two pages with the same layout is
  // the most natural multi-page case there is, and pdf-lib rejects it.
  let fieldId = 0;
  for (const pageSpec of pages) {
    const page = doc.addPage(pageSpec.size ?? DEFAULT_SIZE);
    if (pageSpec.rotation) page.setRotation({ type: 'degrees', angle: pageSpec.rotation });
    if (pageSpec.cropBox) page.setCropBox(...pageSpec.cropBox);
    for (const ink of pageSpec.ink ?? []) drawInk(page, ink);
    for (const widget of pageSpec.widgets ?? []) {
      fieldId += 1;
      addWidget(form, page, widget, fieldId);
    }
    applyAnnotationFlags(page, pageSpec.widgets ?? []);
  }
  return PDFDocument.load(await doc.save(), { ignoreEncryption: true });
}
