import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PDFDocument, PDFName, degrees } from '@cantoo/pdf-lib';
import { beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { detectPageRegions, detectWidgetRegions } from './formGrid.js';
import { collectTextFieldWidgets } from './pdfObjects.js';
import { reconcileFields, withWidgetFields } from './fieldRegions.js';

/**
 * The shipped practice form, against the whole field detector.
 *
 * Every other fixture here is a flat form: no `/AcroForm`, boxes drawn in the
 * page's own content stream, which is what the ink detectors read. This one is
 * the opposite kind and it is the file the product itself hands people, so a
 * regression in it is a regression someone meets on their first visit. Six of
 * its nine fields are visible only as widget rectangles - their borders are
 * painted inside each widget's `/AP /N` appearance stream, which
 * `collectPageInk` does not walk and deliberately does not - so before
 * `detectWidgetRegions` the detector reported 3 of 9 (the comb, whose guide
 * boxes the generator also draws on the page, and the two checkboxes, which
 * `collectCheckboxWidgets` was already reading off `/Annots`).
 *
 * It is generated by `scripts/generate-practice-form.mjs` from
 * `src/tools/redact/practiceFormContent.js`, so these numbers move only when
 * that form's own fields do.
 */
const SAMPLE = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..', '..', '..', '..', 'public', 'images', 'redaction-guide', 'sample.pdf',
);

/** What `useFormFieldRegions` does per page, minus the pdf.js text pass. */
function detectPage(page, pageIndex = 0) {
  const ink = detectPageRegions(page, pageIndex);
  const reconciled = reconcileFields({ combs: ink.combs, checkboxes: ink.checkboxes, cells: [] });
  return {
    ...withWidgetFields({ ...reconciled, checkboxes: ink.checkboxes }, detectWidgetRegions(page, pageIndex)),
    checkboxes: ink.checkboxes,
  };
}

describe('the practice form, end to end', () => {
  let page;
  beforeAll(async () => {
    const doc = await PDFDocument.load(fs.readFileSync(SAMPLE), { ignoreEncryption: true });
    page = doc.getPage(0);
  });

  it('finds every one of its nine fields', () => {
    const { combs, cells, checkboxes } = detectPage(page);
    expect({ combs: combs.length, cells: cells.length, checkboxes: checkboxes.length })
      .toEqual({ combs: 1, cells: 6, checkboxes: 2 });
  });

  it('reports the student ID once, not twice, though both sources see it', () => {
    // The generator paints nine guide boxes into the page stream *and* lays a
    // live comb widget over them, so this field arrives from both sources.
    expect(detectWidgetRegions(page, 0).combs).toHaveLength(1);
    expect(detectPageRegions(page, 0).combs).toHaveLength(1);
    const { combs } = detectPage(page);
    expect(combs).toHaveLength(1);
    expect(combs[0].cells).toBe(9);
  });

  it('carries the page index it was asked for', () => {
    const { combs, cells } = detectPage(page, 3);
    expect([...combs, ...cells].every((region) => region.pageIndex === 3)).toBe(true);
  });
});

describe('collectTextFieldWidgets', () => {
  let doc;
  let page;
  // Reloaded per test, not once: two of these mutate the document, and a test
  // that inherits another's mutation is not proving its own claim.
  beforeEach(async () => {
    doc = await PDFDocument.load(fs.readFileSync(SAMPLE), { ignoreEncryption: true });
    page = doc.getPage(0);
  });

  it('reads the seven text fields and leaves the two buttons alone', () => {
    // `/FT`, `/Ff` and `/MaxLen` all sit on the parent field dict here, never
    // on the widget: reading the widget alone finds nothing at all.
    expect(collectTextFieldWidgets(page)).toHaveLength(7);
  });

  it('takes a comb field\'s cell count from its /MaxLen', () => {
    const comb = collectTextFieldWidgets(page).find((field) => field.combCells);
    expect(comb.combCells).toBe(9);
    expect(Math.round(comb.width)).toBe(225);
  });

  it('skips a hidden widget', () => {
    const widget = doc.context.lookup(page.node.Annots().get(0));
    widget.set(PDFName.of('F'), doc.context.obj(2));
    expect(collectTextFieldWidgets(page)).toHaveLength(6);
  });

  it('skips a read-only widget - nobody can write in one', () => {
    // On `/Ff`, which is inherited: the flag is set on the parent field dict,
    // where a pdf-lib-generated form keeps it, not on the widget.
    const widget = doc.context.lookup(page.node.Annots().get(1));
    const parent = doc.context.lookup(widget.get(PDFName.of('Parent')));
    parent.set(PDFName.of('Ff'), doc.context.obj(1));
    expect(collectTextFieldWidgets(page)).toHaveLength(6);
  });
});

describe('the widget path under rotation and a shifted crop box', () => {
  /** The practice form's widgets, as page percentages, after `mutate(page)`. */
  async function regionsAfter(mutate) {
    const doc = await PDFDocument.load(fs.readFileSync(SAMPLE), { ignoreEncryption: true });
    const page = doc.getPage(0);
    mutate(page);
    return detectWidgetRegions(page, 0);
  }

  it('turns the page percentages with the page', async () => {
    // The practice form is 680x500 landscape and unrotated, so nothing else
    // here exercises the transform `detectPageRegions` shares with this path.
    const upright = await regionsAfter(() => {});
    const turned = await regionsAfter((page) => page.setRotation(degrees(90)));
    const [first] = upright.cells;
    const [rotated] = turned.cells;
    // A 90-degree turn swaps which axis each edge runs along, so a field that
    // was wide and short comes back tall and narrow.
    expect(rotated.width).toBeCloseTo(first.height, 1);
    expect(rotated.height).toBeCloseTo(first.width, 1);
    expect(turned.cells).toHaveLength(upright.cells.length);
  });

  it('measures a widget from the crop box, not the media box', async () => {
    // `/Rect` is in user space; a crop box that does not start at the origin
    // moves where the same rectangle falls as a percentage of what is shown.
    const cropped = await regionsAfter((page) => page.setCropBox(40, 0, 640, 500));
    const plain = await regionsAfter(() => {});
    expect(cropped.cells[0].left).toBeLessThan(plain.cells[0].left);
    expect(cropped.cells[0].width).toBeGreaterThan(plain.cells[0].width);
  });
});

describe('withWidgetFields', () => {
  const box = (left, top, width = 10, height = 4) => ({ pageIndex: 0, left, top, width, height });

  it('keeps the ink answer and drops the widget that overlaps it', () => {
    const ink = { combs: [box(10, 10)], checkboxes: [], cells: [] };
    const widgets = { combs: [{ ...box(10.2, 10.1), cells: 9 }], cells: [] };
    const { combs } = withWidgetFields(ink, widgets);
    expect(combs).toEqual(ink.combs);
  });

  it('adds the widgets nothing else found', () => {
    const ink = { combs: [], checkboxes: [], cells: [box(10, 10)] };
    const widgets = { combs: [], cells: [box(10, 40), box(10, 60)] };
    expect(withWidgetFields(ink, widgets).cells).toHaveLength(3);
  });

  it('does not offer a text cell over a checkbox already found', () => {
    const ink = { combs: [], checkboxes: [box(10, 10, 3, 3)], cells: [] };
    const widgets = { combs: [], cells: [box(10, 10, 3, 3)] };
    expect(withWidgetFields(ink, widgets).cells).toEqual([]);
  });

  it('lets an added comb claim the cell the ink pass called plain text', () => {
    // The weakest thing either side reports is a cell, so a widget saying
    // "nine boxes" beats an ink pass that only found "a closed box here".
    // Leaving both put a text box and a nine-cell comb on one rectangle.
    const ink = { combs: [], checkboxes: [], cells: [{ ...box(10, 10), kind: 'text' }] };
    const widgets = { combs: [{ ...box(10, 10), cells: 9, boxed: true }], cells: [] };
    const { combs, cells } = withWidgetFields(ink, widgets);
    expect(combs).toHaveLength(1);
    expect(cells).toEqual([]);
  });

  it('leaves an ink cell alone when the added comb is somewhere else', () => {
    const ink = { combs: [], checkboxes: [], cells: [{ ...box(10, 10), kind: 'text' }] };
    const widgets = { combs: [{ ...box(10, 40), cells: 9, boxed: true }], cells: [] };
    const { combs, cells } = withWidgetFields(ink, widgets);
    expect(combs).toHaveLength(1);
    expect(cells).toEqual(ink.cells);
  });

  it('does not offer a cell over a comb it just added either', () => {
    const ink = { combs: [], checkboxes: [], cells: [] };
    const widgets = { combs: [{ ...box(10, 10), cells: 9 }], cells: [box(10, 10)] };
    const { combs, cells } = withWidgetFields(ink, widgets);
    expect(combs).toHaveLength(1);
    expect(cells).toEqual([]);
  });

  it('is a no-op on a flat form, which has no widgets at all', () => {
    const ink = { combs: [box(10, 10)], checkboxes: [box(5, 5)], cells: [box(10, 40)] };
    const { combs, cells } = withWidgetFields(ink, { combs: [], cells: [] });
    expect({ combs, cells }).toEqual({ combs: ink.combs, cells: ink.cells });
  });
});
