import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PDFDocument, PDFName } from '@cantoo/pdf-lib';
import { beforeAll, describe, expect, it } from 'vitest';
import { detectPageRegions, detectWidgetRegions } from './formGrid.js';
import { collectTextFieldWidgets } from './pdfObjects.js';
import { reconcileFields, withWidgetFields } from './fieldRegions.js';

/**
 * The shipped practice form, against the whole field detector.
 *
 * Every other fixture here is a flat form: no `/AcroForm`, boxes drawn in the
 * page's own content stream, which is what the ink detectors read. This one is
 * the opposite kind and it is the file the product itself hands people, so a
 * regression in it is a regression someone meets on their first visit. Six of
 * its nine fields are visible only as widget rectangles - their borders are
 * painted inside each widget's `/AP /N` appearance stream, which
 * `collectPageInk` does not walk and deliberately does not - so before
 * `detectWidgetRegions` the detector reported 3 of 9 (the comb, whose guide
 * boxes the generator also draws on the page, and the two checkboxes, which
 * `collectCheckboxWidgets` was already reading off `/Annots`).
 *
 * It is generated by `scripts/generate-practice-form.mjs` from
 * `src/tools/redact/practiceFormContent.js`, so these numbers move only when
 * that form's own fields do.
 */
const SAMPLE = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..', '..', '..', '..', 'public', 'images', 'redaction-guide', 'sample.pdf',
);

/** What `useFormFieldRegions` does per page, minus the pdf.js text pass. */
function detectPage(page, pageIndex = 0) {
  const ink = detectPageRegions(page, pageIndex);
  const reconciled = reconcileFields({ combs: ink.combs, checkboxes: ink.checkboxes, cells: [] });
  return {
    ...withWidgetFields({ ...reconciled, checkboxes: ink.checkboxes }, detectWidgetRegions(page, pageIndex)),
    checkboxes: ink.checkboxes,
  };
}

describe('the practice form, end to end', () => {
  let page;
  beforeAll(async () => {
    const doc = await PDFDocument.load(fs.readFileSync(SAMPLE), { ignoreEncryption: true });
    page = doc.getPage(0);
  });

  it('finds every one of its nine fields', () => {
    const { combs, cells, checkboxes } = detectPage(page);
    expect({ combs: combs.length, cells: cells.length, checkboxes: checkboxes.length })
      .toEqual({ combs: 1, cells: 6, checkboxes: 2 });
  });

  it('reports the student ID once, not twice, though both sources see it', () => {
    // The generator paints nine guide boxes into the page stream *and* lays a
    // live comb widget over them, so this field arrives from both sources.
    expect(detectWidgetRegions(page, 0).combs).toHaveLength(1);
    expect(detectPageRegions(page, 0).combs).toHaveLength(1);
    const { combs } = detectPage(page);
    expect(combs).toHaveLength(1);
    expect(combs[0].cells).toBe(9);
  });

  it('carries the page index it was asked for', () => {
    const { combs, cells } = detectPage(page, 3);
    expect([...combs, ...cells].every((region) => region.pageIndex === 3)).toBe(true);
  });
});

describe('collectTextFieldWidgets', () => {
  let doc;
  let page;
  beforeAll(async () => {
    doc = await PDFDocument.load(fs.readFileSync(SAMPLE), { ignoreEncryption: true });
    page = doc.getPage(0);
  });

  it('reads the seven text fields and leaves the two buttons alone', () => {
    // `/FT`, `/Ff` and `/MaxLen` all sit on the parent field dict here, never
    // on the widget: reading the widget alone finds nothing at all.
    expect(collectTextFieldWidgets(page)).toHaveLength(7);
  });

  it('takes a comb field\'s cell count from its /MaxLen', () => {
    const comb = collectTextFieldWidgets(page).find((field) => field.combCells);
    expect(comb.combCells).toBe(9);
    expect(Math.round(comb.width)).toBe(225);
  });

  it('skips a hidden widget', () => {
    const widget = doc.context.lookup(page.node.Annots().get(0));
    widget.set(PDFName.of('F'), doc.context.obj(2));
    expect(collectTextFieldWidgets(page)).toHaveLength(6);
  });

  it('skips a read-only widget - nobody can write in one', () => {
    const widget = doc.context.lookup(page.node.Annots().get(1));
    const parent = doc.context.lookup(widget.get(PDFName.of('Parent')));
    parent.set(PDFName.of('Ff'), doc.context.obj(1));
    expect(collectTextFieldWidgets(page)).toHaveLength(5);
  });
});

describe('withWidgetFields', () => {
  const box = (left, top, width = 10, height = 4) => ({ pageIndex: 0, left, top, width, height });

  it('keeps the ink answer and drops the widget that overlaps it', () => {
    const ink = { combs: [box(10, 10)], checkboxes: [], cells: [] };
    const widgets = { combs: [{ ...box(10.2, 10.1), cells: 9 }], cells: [] };
    const { combs } = withWidgetFields(ink, widgets);
    expect(combs).toEqual(ink.combs);
  });

  it('adds the widgets nothing else found', () => {
    const ink = { combs: [], checkboxes: [], cells: [box(10, 10)] };
    const widgets = { combs: [], cells: [box(10, 40), box(10, 60)] };
    expect(withWidgetFields(ink, widgets).cells).toHaveLength(3);
  });

  it('does not offer a text cell over a checkbox already found', () => {
    const ink = { combs: [], checkboxes: [box(10, 10, 3, 3)], cells: [] };
    const widgets = { combs: [], cells: [box(10, 10, 3, 3)] };
    expect(withWidgetFields(ink, widgets).cells).toEqual([]);
  });

  it('does not offer a cell over a comb it just added either', () => {
    const ink = { combs: [], checkboxes: [], cells: [] };
    const widgets = { combs: [{ ...box(10, 10), cells: 9 }], cells: [box(10, 10)] };
    const { combs, cells } = withWidgetFields(ink, widgets);
    expect(combs).toHaveLength(1);
    expect(cells).toEqual([]);
  });

  it('is a no-op on a flat form, which has no widgets at all', () => {
    const ink = { combs: [box(10, 10)], checkboxes: [box(5, 5)], cells: [box(10, 40)] };
    const { combs, cells } = withWidgetFields(ink, { combs: [], cells: [] });
    expect({ combs, cells }).toEqual({ combs: ink.combs, cells: ink.cells });
  });
});
