#!/usr/bin/env node
// ARCH-30: the iteration check. Same source guards and the same unit oracle
// (scripts/unit-scope.mjs) that check:push and CI use, with two differences
// measured on 2026-09-26 (backlog/tasks/ARCH-30.md):
//
//   --since <ref>  scopes the unit tests to what changed since <ref> (the
//                  working tree against it, untracked files included), so a
//                  subagent the lead hands a task's starting commit tests its
//                  own edit, not everything its branch has changed since main.
//                  Without it the base is the merge-base with origin/main, as
//                  before. An unresolvable ref fails open to the whole suite.
//
//   typecheck      `astro check` costs 18-21s whatever changed. `tsc --noEmit`
//                  with an incremental cache costs 5s cold and 2s warm and
//                  catches the same `.ts` errors, but not `.astro` files. So
//                  the loop runs tsc, and `astro check` whenever the same diff
//                  touches something only it can see (chooseTypecheck below).
//                  check:push and CI keep `astro check`, whole branch.
//
// It ends with one summary line, so an agent never re-runs it to find out
// whether it passed.
//
// Usage: npm run check:fast [-- --since <ref>]

import { existsSync, mkdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve as resolvePath } from 'node:path';
import { resolveBase, changedFilesWithStatus } from './change-scope.mjs';
import { selectUnitTests, runUnitByImpact } from './unit-scope.mjs';

const ROOT = resolvePath(dirname(fileURLToPath(import.meta.url)), '..');

// The cheap source guards check:fast has always run, in the same order.
export const GUARD_STEPS = [
  'check:backlog',
  'check:guidance',
  'test:editor-dependency-directions',
  'test:module-boundaries',
  'test:gesture-golden-rule',
  'test:detection-purity',
  'check-class-resolution',
];

// What tsc cannot see or would see stale: `.astro` files themselves, the
// configs that shape type resolution, the content schema behind
// `.astro/types.d.ts`, and this file (never trust a narrowed run to validate
// the code that chose to narrow it).
export const ASTRO_CHECK_TRIGGERS = [
  /\.astro$/,
  /^tsconfig(\..+)?\.json$/,
  /^astro\.config\.mjs$/,
  /^package(-lock)?\.json$/,
  /^src\/content\.config\.ts$/,
  /^scripts\/check-fast\.mjs$/,
];

// Pure. `files` is the changed-path list, or null when the base could not be
// resolved; `astroTypesExist` says whether `.astro/types.d.ts` (generated by
// astro, included by tsconfig) is on disk for tsc to read.
export function chooseTypecheck({ files, astroTypesExist }) {
  if (files === null) return { tool: 'astro', reason: 'no usable base' };
  if (!astroTypesExist) return { tool: 'astro', reason: '.astro/types.d.ts not generated yet' };
  const hits = files.filter((f) => ASTRO_CHECK_TRIGGERS.some((re) => re.test(f)));
  if (hits.length > 0) return { tool: 'astro', reason: `only astro check sees ${hits.join(', ')}` };
  return { tool: 'tsc', reason: 'no .astro or type-config change' };
}

// Pure. Returns { since } or { error }.
export function parseArgs(argv) {
  const i = argv.indexOf('--since');
  if (i < 0) return { since: undefined };
  const since = argv[i + 1];
  if (!since || since.startsWith('--')) return { error: '--since needs a ref (the commit the task started from)' };
  return { since };
}

// Pure. One line: verdict, total, base, per-step seconds.
export function summaryLine({ ok, failed, base, since, steps }) {
  const total = steps.reduce((sum, s) => sum + s.seconds, 0);
  const verdict = ok ? 'PASS' : `FAIL at ${failed}`;
  const scope = since ? `since ${since}` : `since merge-base ${base ? base.slice(0, 7) : '(none)'}`;
  const parts = steps.map((s) => `${s.name} ${s.seconds.toFixed(1)}s${s.detail ? ` (${s.detail})` : ''}`);
  return `check:fast ${verdict} in ${total.toFixed(1)}s, ${scope}: ${parts.join(', ')}`;
}

// ---------------------------------------------------------------------------
// I/O below: git, npm and npx subprocesses. The pure parts above are pinned by
// scripts/check-fast.test.mjs.

function run(cmd, args) {
  return spawnSync(cmd, args, { stdio: 'inherit', cwd: ROOT }).status ?? 1;
}

function runGuard(step) {
  if (step === 'check-class-resolution') return run('node', ['scripts/check-class-resolution.js']);
  return run('npm', ['run', '-s', step]);
}

function runTypecheck(tool) {
  if (tool === 'astro') return run('npx', ['astro', 'check']);
  const cacheDir = join(ROOT, 'node_modules', '.cache');
  mkdirSync(cacheDir, { recursive: true });
  return run('npx', ['tsc', '--noEmit', '-p', '.', '--incremental', '--tsBuildInfoFile', join(cacheDir, 'check-fast.tsbuildinfo')]);
}

function timed(fn) {
  const start = performance.now();
  const status = fn();
  return { status, seconds: (performance.now() - start) / 1000 };
}

function main(argv) {
  const args = parseArgs(argv);
  if (args.error) {
    console.error(`check:fast: ${args.error}`);
    return 2;
  }

  const base = resolveBase(args.since);
  const files = base ? changedFilesWithStatus(base) : null;
  const unitScope = files
    ? selectUnitTests({ files, exists: (p) => existsSync(join(ROOT, p)) })
    : { all: true, seeds: [], reasons: [`no usable base (${args.since ?? 'origin/main'})`] };
  const typecheck = chooseTypecheck({
    files: files && files.map((f) => f.path),
    astroTypesExist: existsSync(join(ROOT, '.astro', 'types.d.ts')),
  });

  const plan = [
    { name: 'guards', run: () => GUARD_STEPS.reduce((status, step) => status || runGuard(step), 0) },
    {
      name: 'units',
      detail: unitScope.all ? 'full suite' : `${unitScope.seeds.length} seeds`,
      run: () => {
        console.error(`check:fast units: ${unitScope.reasons.join(' | ')}`);
        return runUnitByImpact(unitScope);
      },
    },
    {
      name: typecheck.tool === 'tsc' ? 'tsc' : 'astro check',
      run: () => {
        console.error(`check:fast typecheck: ${typecheck.tool} (${typecheck.reason})`);
        return runTypecheck(typecheck.tool);
      },
    },
  ];

  const steps = [];
  let failed;
  for (const step of plan) {
    const { status, seconds } = timed(step.run);
    steps.push({ name: step.name, seconds, detail: step.detail });
    if (status !== 0) {
      failed = step.name;
      break;
    }
  }

  console.log(`\n${summaryLine({ ok: !failed, failed, base, since: args.since, steps })}`);
  return failed ? 1 : 0;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  process.exit(main(process.argv.slice(2)));
}
