#!/usr/bin/env node
// SEO-02: reproduces the section 3 standings tables (3.1 to 3.3) in
// docs/seo-competitive-findings.md from a Search Console export, so the
// next refresh follows a recipe instead of re-deriving a compatible-looking
// method. Manual steps this script does not (and cannot) do are in the
// refresh procedure (section 6 of the findings doc), not here.
//
// LOC-06 added section 3.7 (by locale): pages grouped by URL prefix from
// src/i18n/localePrefixes.js next to their English sibling, non-Latin
// queries clustered by detected script instead of the English-intent
// CLUSTER_PATTERNS below, and a country breakdown for each locale's pilot
// country (src/i18n/localePrefixes.js's pilotCountry map). The pure logic
// for all of that lives in scripts/seoRefreshLib.mjs, unit-tested from
// src/lib/seoRefresh.test.js.
//
// Usage:
//   node scripts/seo-refresh.mjs <path to the "Performance on Search" export folder>
//
// That folder is what Search Console's Performance report exports as a zip
// when you: open Search Console -> Performance -> Search results, set
// Search type = Web, Date = Last 3 months, then Export -> CSV, and unzip it.
// This script reads Queries.csv, Pages.csv, Countries.csv and Devices.csv
// from inside it (Chart.csv, Filters.csv and Search appearance.csv are not
// used here).
//
// What this script cannot do: assign a "who ranks above us" competitor
// column (section 3.5) - that stays a manual SERP check, same limitation
// SEO-04/SEO-05 hit (Google blocks scripted/automated SERP fetches). It also
// cannot get an exact site-wide query count - see the privacy-filtering note
// below - so cluster totals from this script are a documented lower bound,
// not the authoritative number. The authoritative site-wide and per-page
// totals are the Pages.csv sums, which are printed here too and are exact.
import { readFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import {
  parseCsv,
  weightedPosition,
  groupQueriesByScript,
  groupPagesByLocale,
  countryRowForLocale,
} from './seoRefreshLib.mjs';

async function readCsv(dir, filename) {
  const text = await readFile(join(dir, filename), 'utf8');
  return parseCsv(text);
}

// One row per cluster in section 3.1's "By intent cluster" table. Order here
// is the order printed. A query can match more than one pattern (e.g.
// "compress password protected pdf" reads as both compress- and
// unlock-intent); that overlap is accepted, not deduplicated, because
// forcing single-cluster membership would be a judgment call this script
// has no basis to make consistently.
const CLUSTER_PATTERNS = [
  ['blur / redact', /blur|blackout|black out|redact|blacked out|blurr|censor|pixelate/i],
  ['compress to a size', /compress|100\s*kb|reduce.*size|file size|document size/i],
  ['sign', /\bsign\b|signature|signed/i],
  ['split / extract', /split|extract|divide|\bcut\b/i],
  ['unlock', /unlock|password|protect/i],
  ['merge', /merge|combine|gabung/i],
];

function fmt(n, digits = 1) {
  return n === null ? '-' : n.toFixed(digits);
}

async function main() {
  const exportDir = process.argv[2];
  if (!exportDir) {
    console.error('Usage: node scripts/seo-refresh.mjs <path to the Performance-on-Search export folder>');
    process.exit(1);
  }
  const dir = resolve(exportDir);

  const queries = await readCsv(dir, 'Queries.csv');
  const pages = await readCsv(dir, 'Pages.csv');
  const countries = await readCsv(dir, 'Countries.csv').catch(() => null);
  const devices = await readCsv(dir, 'Devices.csv').catch(() => null);

  const queryImpressionsTotal = queries.reduce((s, r) => s + Number(r.Impressions), 0);
  const pageImpressionsTotal = pages.reduce((s, r) => s + Number(r.Impressions), 0);
  const pageClicksTotal = pages.reduce((s, r) => s + Number(r.Clicks), 0);

  console.log('# Section 1 refresh - generated by scripts/seo-refresh.mjs\n');
  console.log(
    `Web search only. ${pageClicksTotal} clicks, ~${pageImpressionsTotal} impressions site-wide (from Pages.csv, the authoritative per-page total).`,
  );
  console.log(
    `Queries.csv sums to ${queryImpressionsTotal} impressions - ${(
      (1 - queryImpressionsTotal / pageImpressionsTotal) *
      100
    ).toFixed(0)}% short of the page total. This is expected: Search Console omits some individual` +
      ' queries from the query-level report to protect searcher privacy (documented Google behaviour,' +
      ' not a gap in this script). It hits small clusters hardest, since a few omitted low-impression' +
      ' queries are a bigger share of a small total. Read the cluster table below as a lower bound,' +
      ' and the By page table (straight from Pages.csv) as the exact number.\n',
  );

  console.log('### By intent cluster\n');
  console.log('| Cluster | Clicks | Impressions | Weighted position | Unclassified queries this pattern missed |');
  console.log('| --- | ---: | ---: | ---: | --- |');
  const matchedQueryTexts = new Set();
  for (const [name, pattern] of CLUSTER_PATTERNS) {
    const rows = queries.filter((r) => pattern.test(r['Top queries']));
    rows.forEach((r) => matchedQueryTexts.add(r['Top queries']));
    const clicks = rows.reduce((s, r) => s + Number(r.Clicks), 0);
    const impressions = rows.reduce((s, r) => s + Number(r.Impressions), 0);
    const wp = weightedPosition(rows);
    console.log(`| ${name} | ${clicks} | ${impressions} | ${fmt(wp)} | |`);
  }

  const unclassified = queries
    .filter((r) => !matchedQueryTexts.has(r['Top queries']) && Number(r.Impressions) >= 2)
    .sort((a, b) => Number(b.Impressions) - Number(a.Impressions));
  if (unclassified.length) {
    console.log('\nUnclassified queries with >=2 impressions (check these are genuinely off-topic, not a missed cluster):');
    for (const r of unclassified) {
      console.log(`  - "${r['Top queries']}" - ${r.Impressions} impressions, position ${r.Position}`);
    }
  }

  console.log('\n### By page (exact - from Pages.csv)\n');
  console.log('| Page | Clicks | Impressions | CTR | Position |');
  console.log('| --- | ---: | ---: | ---: | ---: |');
  for (const r of pages) {
    const page = r['Top pages'].replace('https://pdkef.com', '') || '/';
    console.log(`| \`${page}\` | ${r.Clicks} | ${r.Impressions} | ${r.CTR} | ${Number(r.Position).toFixed(2)} |`);
  }

  if (countries) {
    console.log('\n### By country (top 6 by clicks, exact - from Countries.csv)\n');
    console.log('| Country | Clicks | Impressions | CTR | Position |');
    console.log('| --- | ---: | ---: | ---: | ---: |');
    for (const r of countries.slice(0, 6)) {
      console.log(`| ${r.Country} | ${r.Clicks} | ${r.Impressions} | ${r.CTR} | ${Number(r.Position).toFixed(2)} |`);
    }
  }

  if (devices) {
    console.log('\n### By device (exact - from Devices.csv)\n');
    console.log('| Device | Clicks | Impressions | CTR | Position |');
    console.log('| --- | ---: | ---: | ---: | ---: |');
    for (const r of devices) {
      console.log(`| ${r.Device} | ${r.Clicks} | ${r.Impressions} | ${r.CTR} | ${Number(r.Position).toFixed(2)} |`);
    }
  }

  // LOC-06: which non-English queries appear at all, and how each localized
  // page performs against its English sibling. Paste this whole block over
  // findings doc section 3.7 - replace, do not append, same rule as the
  // other section 3 tables.
  console.log('\n### 3.7 By locale\n');
  console.log(
    'Same privacy-filter caveat as the by-intent table above, more so here: a locale with only a' +
      ' handful of impressions has proportionally more of its queries omitted by the privacy filter,' +
      ' so the query list below is a lower bound on what it actually receives - more than usual, since' +
      " a small locale's whole query list can sit under the filter's threshold. Pages.csv counts below" +
      ' are exact, same as the By page table above.\n',
  );

  const localeGroups = groupPagesByLocale(pages);
  if (!localeGroups.length) {
    console.log(
      'No localized page (a URL under a prefix in src/i18n/localePrefixes.js) appears in Pages.csv this period.\n',
    );
  }
  for (const { prefix, pilotCountry, pages: localePages } of localeGroups) {
    console.log(`#### /${prefix}/ pages vs. their English sibling\n`);
    console.log(
      '| Page | Clicks | Impressions | CTR | Position | English sibling | Sibling clicks | Sibling impressions | Sibling CTR | Sibling position |',
    );
    console.log('| --- | ---: | ---: | ---: | ---: | --- | ---: | ---: | ---: | ---: |');
    for (const p of localePages) {
      const sib = p.sibling;
      console.log(
        `| \`${p.path}\` | ${p.clicks} | ${p.impressions} | ${p.ctr} | ${p.position.toFixed(2)} | ` +
          `${sib ? `\`${sib.path}\`` : `\`${p.siblingPath}\` (no impressions this period)`} | ${
            sib ? sib.clicks : '-'
          } | ${sib ? sib.impressions : '-'} | ${sib ? sib.ctr : '-'} | ${sib ? sib.position.toFixed(2) : '-'} |`,
      );
    }

    if (pilotCountry) {
      const countryInfo = countryRowForLocale(countries, prefix);
      console.log(`\nPilot country for /${prefix}/: ${pilotCountry} (src/i18n/localePrefixes.js's pilotCountry map).`);
      if (countryInfo?.row) {
        const r = countryInfo.row;
        console.log(
          `${pilotCountry}: ${r.Clicks} clicks, ${r.Impressions} impressions, ${r.CTR} CTR, position ${Number(
            r.Position,
          ).toFixed(2)} (from Countries.csv, site-wide - not filtered to /${prefix}/ pages, since Search Console` +
            ' does not cross-filter Countries.csv by page).',
        );
      } else {
        console.log(`${pilotCountry} has no row in Countries.csv this period (zero, or below the export's threshold).`);
      }
    }
    console.log('');
  }

  console.log('#### Non-Latin queries, by script\n');
  console.log(
    'Every query in Queries.csv is its own row here (not deduplicated across pages), grouped by the' +
      ' first non-Latin script it contains - the direct test of whether the phrasing LOC-01 predicted' +
      ' is what actually arrived.\n',
  );
  const scriptGroups = groupQueriesByScript(queries);
  if (!scriptGroups.length) {
    console.log('No query in Queries.csv this period carries a non-Latin script (see the privacy-filter caveat above).');
  }
  for (const { script, rows, clicks, impressions, weightedPosition: wp } of scriptGroups) {
    console.log(`**${script}** - ${clicks} clicks, ${impressions} impressions, weighted position ${fmt(wp)}:`);
    for (const r of rows) {
      console.log(`  - "${r['Top queries']}" - ${r.Clicks} clicks, ${r.Impressions} impressions, position ${r.Position}`);
    }
  }
}

main();
